baseurl = "https://selvasoft.in"
title = "Peratchiselvan (Selva)"

theme = "hello-friend-ng"

languagecode = "en"
defaultcontentlanguage = "en"

canonifyurls = true

pygmentscodefences = false
pygmentscodefencesguesssyntax = true

disqusShortname = ""
enableRobotsTXT = true

[params]
    author = "Selva"
    homeSubtitle = "App Developer"
    description = "Software | Life | Scripts"
    keywords = "blog,developer,personal"
    footercontent = ""

    dateformat = "January 2, 2006"
    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false
    defaultTheme = "light"
    [params.logo]
        logoText     = "HOME"
        logoHomeLink = "/"
  # Social icons
  [[params.social]]
    name = "telegram"
    url  = "https://telegram.me/selvasoft"

  [[params.social]]
    name = "email"
    url  = "mailto:selva@selvasoft.in"

  [[params.social]]
    name = "github"
    url  = "https://github.com/peratchiselvan"

  [[params.social]]
    name = "whatsapp"
    url  = "https://wa.me/916382882364"

    # Custom CSS
    custom_css = []

[taxonomies]
  series = "series"


[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"


