baseURL = "https://jovial-newton-c5194c.netlify.app/"
title = "selva"

theme = "selva"
canonifyurls = true
pygmentscodefences = false
pygmentscodefencesguesssyntax = true
[markup.goldmark.renderer]
unsafe= true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"


[taxonomies]
  tag = "tags"

[params]
  authorName = "Selva"
